name: Ardrive Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: |
         echo "Installing Dependencies....!"
      - name: Build the static website
        run: |
         cd static-website
         npm install
         npm run build
         ls
      - name: Upload to Ardrive
        run: |
         echo "Uploading to Ardrive....!"
        #  ardrive --help
      - name: Creating a Manifest
        run: |
          echo "Creating a manifest....!"
          echo "Manifest created Successfully!"