name: Build the static Website
run-name: ${{ github.actor }} is building and pushing into ardrive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17'
      - name: Install Ardrive
        run: |
          echo "Latest Ardrive installed"