name: Test for create new file
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Ardrive
        run: |
          echo "Latest Ardrive installed"